resources:
- repo: self
  clean: true
queue:
  name: VSEng-MicroBuildVS2017
  demands: Cmd

variables:
  DropRoot: '\\cpvsbuild\drops'
  BuildConfiguration: Release
  BuildPlatform: 'any cpu'
  RunningInMicroBuild: true
  TeamName: Roslyn

steps:
- task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
  displayName: 'Install Signing Plugin'
  inputs:
    signType: real

- task: ms-vseng.MicroBuildTasks.32f78468-e895-4f47-962c-58a699361df8.MicroBuildSwixPlugin@1
  displayName: 'Install Swix Plugin'
  inputs:
    dropName: 'Products/$(System.TeamProject)/dotnet-getting-started-templates/$(Build.SourceBranchName)/$(Build.BuildNumber)'

- script: eng\common\CIBuild.cmd 
          -configuration $(BuildConfiguration)
          /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
          /p:VisualStudioDropName=$(VisualStudioDropName) # required if repository builds VS insertion components
          /p:DotNetSignType=$(SignType)
          /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
          /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
  displayName: Build

- task: ms-vseng.MicroBuildTasks.4305a8de-ba66-4d8b-b2d1-0dc4ecbbf5e8.MicroBuildUploadVstsDropFolder@1
  displayName: 'Upload VSTS Drop'
  inputs:
    DropFolder: 'artifacts\VSSetup\$(BuildConfiguration)\Insertion'

- task: CopyPublishBuildArtifacts@1
  displayName: 'Publish Drop'
  inputs:
    CopyRoot: '$(Build.SourcesDirectory)'
    Contents: |
     artifacts\bin
     artifacts\log\$(BuildConfiguration)
     artifacts\VSSetup\$(BuildConfiguration)
    ArtifactName: '$(Build.BuildNumber)'
    ArtifactType: FilePath
    TargetPath: '$(DropRoot)\Roslyn\$(Build.DefinitionName)'


- task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
  displayName: 'Execute cleanup tasks'

- task: PublishBuildArtifacts@1
  displayName: 'Publish MicroBuild Outputs'
  inputs:
    PathtoPublish: '$(Build.StagingDirectory)\MicroBuild\Output'
    ArtifactName: '$(Build.BuildNumber)'
    publishLocation: FilePath
    TargetPath: '$(DropRoot)\$(TeamName)\$(Build.DefinitionName)'



